#Minecraft server properties
#Wed Aug 19 13:46:27 GMT 2026
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
debug=false
difficulty=hard
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=4078373055178575627
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=xE3J7bYDmtcOh0aSrVFohIlPsLNLHeagSjFY1HNj
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=48
max-tick-time=60000
max-world-size=29999984
motd=§x§5§e§4§f§a§2§l⛰§x§6§b§5§5§9§b§l §x§7§9§5§b§9§4§lE§x§8§7§6§1§8§e§lv§x§9§5§6§8§8§7§le§x§a§3§6§e§8§0§lr§x§b§1§7§4§7§a§le§x§b§f§7§a§7§3§ls§x§c§d§8§1§6§c§lt§x§d§b§8§7§6§6§l §x§e§9§8§d§5§f§lM§x§f§7§9§4§5§9§lC\n§7▶ Survival, Build, Explore
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=14
white-list=false
